### ISSUE TITLE
v2.1.0-beta.4 Crash when adding out of sequence Universes for snapshot (in same window or secondary window)

### ISSUE THREAD

**Issue by abbytutorow** [docsteer/sacnview#199] opened 2019-09-13 19:36 UTC
Screenshot example below. The highlighted 54, I attempted to change to 101, and it crashed. This also happens if I use in-sequence numbers in one snapshot window, and open a second snapshot window and try to change the universe number in that.

![image](https://user-images.githubusercontent.com/29414081/64889529-2a211c80-d633-11e9-924c-ec04fd20f549.png)

I tried to upload the dump file here, but it wouldn't allow the extension. Temporarily, it can be found here:
https://etclink-my.sharepoint.com/:u:/g/personal/abby_tutorow_etcconnect_com/EQCzAY_-B21No9o5bvc0pLkBKa-QK1ZM6DX9KYsuwSZ7KQ?e=ASLg9W

**Comment by marcusbirkin** [comment] 2019-09-14 19:45
Duplicate of #197

**Closed by marcusbirkin** 2019-09-14 19:45 UTC
