### ISSUE TITLE
Update checker crash on start

### ISSUE THREAD

**Issue by Jchuchla** [docsteer/sacnview#97] opened 2017-11-15 20:44 UTC
I just tried to install this on my office desktop.  As soon as it opens the form to select your network interface, I get a fatal crash.  It indicates something with ntdll.dll.  That leads me to believe it's taking some sort of issue with my network interfaces.

I can't get this to run on this machine.  Is the old version still available as a fallback?

**Comment by marcusbirkin** [comment] 2017-11-18 18:00
Which version of Windows are you running?

**Comment by Jchuchla** [comment] 2017-11-18 18:20
This one is win 10 x64 pro. But it works fine on other machines with the same windows version.
I suspect it has something to do with my network adapters on this machine.  This machine has several adapters created by VPN services and such. There’s only one physical NIC but something like 8 virtual connections for various vpns.

--Jon Chuchla--

Sent from my iPhone

On Nov 18, 2017, at 12:00 PM, marcusbirkin <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of Windows are you running?

**Comment by marcusbirkin** [comment] 2017-11-18 21:59
If you disable all the other interfaces from control panel (temporally) does it then start?
Could you also post the output from: ipconfig /all

**Comment by Jchuchla** [comment] 2017-11-18 23:31
I’ll do that when im back to the office next week.  That was my office machine.


--Jon Chuchla--

Email: jon@chuchla.com
Mobile: 708-280-6744

**Comment by Jchuchla** [comment] 2017-12-06 19:07
I totally forgot to get back to this.
Here’s the last screen I see before it locks up.
[cid:image001.png@01D36E91.9F3E9B70]
It locks up before ever allowing me to click anything.

I’ve gone through and disabled all network interfaces except for my primary Ethernet interface and I still get the lockups.

Is the old sacnview version available for download anywhere anymore?

--Jon Chuchla--

**Comment by dtdickman** [comment] 2018-01-03 15:02
I am having a similar issue here. The program opened once without issue, but since the second attempt at opening the software, it crashes immediately. Every time I try to open now, I am prompted with a pop up saying "sACNview.exe has stopped working" and I am forced to close the program.

Running Windows 7 Enterprise. 64 Bit.

**Comment by marcusbirkin** [comment] 2018-01-03 21:24
@Jchuchla and @dtdickman could you both create .DMP files using task manager, as detailed here: https://support.microsoft.com/en-gb/help/931673/how-to-create-a-user-mode-process-dump-file-in-windows and then post them here.

n.b. I think replying directly to the github email will strip the attachments out, so please use the webform.

**Comment by Jchuchla** [comment] 2018-01-03 21:35
Sorry, I cannot from this machine.  Security policies prevent me from sharing a dump from this machine.

**Comment by dtdickman** [comment] 2018-01-03 21:39
I just tried to upload but its a 105MB file. GitHub only allows 10mb
uploads.

**Comment by marcusbirkin** [comment] 2018-01-04 06:37
@dtdickman are you able to upload the .DMP to a cloud service like Dropbox, Google Drive, etc?

**Comment by marcusbirkin** [comment] 2018-01-04 09:16
@Jchuchla using https://docs.microsoft.com/en-us/sysinternals/downloads/debugview could you send me the text capture from this?
The capture is in text format so can be checked for sensitive information.

**Comment by Jchuchla** [comment] 2018-01-04 14:15
[sacnviewDebugLog_01-04-2018.LOG](https://github.com/docsteer/sacnview/files/1603538/sacnviewDebugLog_01-04-2018.LOG)
Thanks for understanding.  Here's the debug log.

**Comment by dtdickman** [comment] 2018-01-04 16:42
https://www.dropbox.com/s/wc10kpyvjdklpu9/sACNView.DMP?dl=0

**Comment by marcusbirkin** [comment] 2018-01-04 17:26
@Jchuchla - Can I assume that's the entire log from start of sACNview to
crash?
Could you try opening sACNView with the route to the internet blocked. So
either one, some, or all; of the following:
() Disable/unplug the adapter with internet access
() Remove the default gateway and DNS from the internet interface
() Block the application completely in Windows firewall


On 4 Jan 2018 14:15, "Jchuchla" <notifications@github.com> wrote:

sacnviewDebugLog_01-04-2018.LOG
<https://github.com/docsteer/sacnview/files/1603538/sacnviewDebugLog_01-04-2018.LOG>
Thanks for understanding. Here's the debug log.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/docsteer/sacnview/issues/97#issuecomment-355292493>,
or mute
the thread

**Comment by Jchuchla** [comment] 2018-01-04 17:32
I disabled the Ethernet adapter (the one connected to the internet) and it then starts successfully.  That doesn’t particularly help me though, because then the interface I need to use is not available.  Hopefully that helps you correct the problem though.

**Comment by marcusbirkin** [comment] 2018-01-04 17:55
I think it might help us...
Do you happen to connect to the web via a proxy server?


On 4 Jan 2018 17:32, "Jchuchla" <notifications@github.com> wrote:

I disabled the Ethernet adapter (the one connected to the internet) and it
then starts successfully. That doesn’t particularly help me though, because
then the interface I need to use is not available. Hopefully that helps you
correct the problem though.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/docsteer/sacnview/issues/97#issuecomment-355346514>,
or mute
the thread

**Comment by Jchuchla** [comment] 2018-01-04 18:31
No proxy.  It’s a pretty standard office configuration.

There is local DNS server, but it forwards requests for all non-local zones to a dns server on the internet.

--Jon Chuchla--

**Comment by marcusbirkin** [comment] 2018-01-04 18:46
If you just remove the default gateway and DNS settings from this interface
(i.e. keep the interface up, but deny internet traffic) does it start?

On 4 Jan 2018 18:31, "Jchuchla" <notifications@github.com> wrote:

No proxy. It’s a pretty standard office configuration.

There is local DNS server, but it forwards requests for all non-local zones
to a dns server on the internet.


--Jon Chuchla--

**Comment by Jchuchla** [comment] 2018-01-04 18:50
Yes it does.  I tested by setting just an IP and subnet mask for the interface leaving gateway and DNS blank

--Jon Chuchla--

**Comment by marcusbirkin** [comment] 2018-01-04 18:52
Bingo!
I'll see if I can reproduce and fix.
Are you able to run a test build if I post one?

**Comment by Jchuchla** [comment] 2018-01-04 18:53
I should be able to.

--Jon Chuchla--

**Comment by marcusbirkin** [comment] 2018-01-05 11:37
Could you try this build: https://www.dropbox.com/s/7cdgdoh00co36yc/sACNView_Jchuchla-05_01_2018.exe

**Comment by Jchuchla** [comment] 2018-01-05 14:25
This build appears to be working.

--Jon Chuchla--

**Comment by marcusbirkin** [comment] 2018-01-05 16:54
Thanks - That isolates the issue to the update checker.
Not totally sure what's the exact issue is yet.

@dtdickman - Does this build also work for you?

**Comment by dtdickman** [comment] 2018-01-05 17:17
Won't be able to test on my PC until Monday. Will get back to you next
week.

**Comment by dtdickman** [comment] 2018-01-09 21:44
That build didn't work for me. Crashes immediately. Tried disabling all network adapters and still crashes as soon as I launch.

**Comment by marcusbirkin** [comment] 2018-01-10 07:06
@dtdickman That's disappointing, looks like yours is a separate issue.
Could you also attach the output from https://docs.microsoft.com/en-us/sysinternals/downloads/debugview

**Comment by dtdickman** [comment] 2018-01-10 16:01
Here ya go. 
[sACNdebug10-1-18.LOG](https://github.com/docsteer/sacnview/files/1619526/sACNdebug10-1-18.LOG)

**Comment by marcusbirkin** [comment] 2018-01-10 17:19
So this log is from the release version (2.0.0) with all interfaces enabled or disabled?

**Comment by dtdickman** [comment] 2018-01-10 18:37
Sorry for the confusion, that log was from your 5-1-18 test build with all adapters enabled.

**Comment by marcusbirkin** [comment] 2018-01-10 20:45
Ah, just for comparison could you do a log using release with and without network adapters enabled?

**Comment by dtdickman** [comment] 2018-01-10 21:30
Wierd, Now 2.0 is crashing with or without adapters enabled.

2.0 log with adapters 
[sACNView2.0-AdaptersEnabled.LOG](https://github.com/docsteer/sacnview/files/1620512/sACNView2.0-AdaptersEnabled.LOG)

2.0 log without adapters
[sACNView2.0-AdaptersDisabled.LOG](https://github.com/docsteer/sacnview/files/1620514/sACNView2.0-AdaptersDisabled.LOG)

**Comment by marcusbirkin** [comment] 2018-01-11 18:13
Could you delete the settings path for sACNView from the registry?

**Comment by dtdickman** [comment] 2018-01-12 20:31
After deleting the settings path from the registry, the program successfully reopens. But once I close the the program and attempt reopening, it crashes again.

**Comment by marcusbirkin** [comment] 2018-01-13 14:39
Could you try deleting each key individually to assertain exactly which key is causing the issue?

**Comment by dtdickman** [comment] 2018-01-16 16:35
It seems that the Mac Address key is causing the issue.

**Comment by marcusbirkin** [comment] 2018-01-18 12:25
@dtdickman as yours is a different issue, i've created #104

**Comment by marcusbirkin** [comment] 2018-01-28 18:44
@Jchuchla 
With the release build of sACNView 2.0.0 (http://docsteer.github.io/sacnview/)
Could you place the .dll files contained with in this .zip: https://indy.fulgan.com/SSL/openssl-1.0.2n-i386-win32.zip into the application directory?

**Comment by Jchuchla** [comment] 2018-01-29 14:18
This works.  No crash on load with those files in the application folder.
--Jon Chuchla--

**Comment by marcusbirkin** [comment] 2018-01-29 18:55
Brilliant! I'll roll these into the next build.
Thanks for the testing!

**Comment by marcusbirkin** [comment] 2018-01-30 21:08
Resolved in v2.0.1-RC1

**Closed by marcusbirkin** 2018-01-30 21:08 UTC
